#! /bin/bash

set -euo pipefail

cp "./target/${1:-debug}/yt-dlp-wrapper" "/home/$USER/.local/bin/yt-dlp-wrapper"
echo "Copied ./target/${1:-debug}/yt-dlp-wrapper to /home/$USER/.local/bin/yt-dlp-wrapper"

cp './yt-dlp-wrapper-submit-request' "/home/$USER/.local/bin/yt-dlp-wrapper-submit-request"
echo "Copied ./yt-dlp-wrapper-submit-request to /home/$USER/.local/bin/yt-dlp-wrapper-submit-request"
